"""Update models

Revision ID: 7fe68f8060ce
Revises: d8b57d6f95eb
Create Date: 2025-09-05 20:12:01.306071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe68f8060ce'
down_revision = 'd8b57d6f95eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('website_link')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('website')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.alter_column('seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('genres',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('website')

    # ### end Alembic commands ###
